services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: idkwhyureadthis
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: prac-project

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U idkwhyureadthis -d practice-project"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  parser:
    build: parser/
    environment:
      SERVER_PORT: 8080
      DATABASE_URL: postgresql://idkwhyureadthis:12345@db:5432/prac-project
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db


  tgbot:
    build: tgbot/
    environment:
      TOKEN:


volumes:
  postgres_data: