services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: idkwhyureadthis
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: prac-project
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  parser:
    build: parser/
    environment:
      SERVER_PORT: 8080
      DATABASE_URL: postgresql://idkwhyureadthis:12345@db:5432/prac-project
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db


  tgbot:
    build: tgbot/
    environment:
      TOKEN: 7263208833:AAEYVyCBa9237BzJ4LUQf_AEF4hvUHI_VIQ


volumes:
  postgres_data: